<?php
    //view helper om aan te geven waar de layout gebruik van maakt.
    echo $this->head()
        ->meta('Author', 'Wesley Overdijk')
        ->addCss($this->themePath.'/css/default.css')
        ->titleSeperator(' - ')
        ->appendTitle('Some random page title.')
        ->setContentType()
        ->appendTitle('An adition to the page title')
        ->disableCache();
?>
<body>
    <div id="pageWrapper">
        <div id="header">
            <h1>Page not found</h1>
        </div>
        <div id="main">
            The page you were looking for was not found. You could try the search though!
            <?php echo $this->search(); ?>
        </div>
        <div id="footer">
            <p><?php echo $this->footer; ?></p>
        </div>
    </div>
</body>
</html>