<html>
<head>
    <title>ZfCms</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="css/style.css" media="all" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="pageWrapper">
        <div id="header">
            <p>#header</p>
        </div>
        <div id="nav">
            <p>#nav</p>
        </div>
        <div id="sidebar">
            <div id="subNav">
                <p>#subNav</p>
            </div>
            <div id="adminMenu">
                <p>#adminMenu</p>
            </div>
            <div id="userForm">
                <p>#userForm</p>
            </div>
                <p>#sidebar</p>
        </div>
        <div id="main">
            <h1>
                Pagetitle
            </h1>
            <h2>
                Some description
            </h2>
            <p>
                Content goes here.
            </p>
        </div>
        <div id="footer">
            <p>Copyright 2009/ 2010. blabla All rights reserved. Powered by xswcms</p>
        </div>
    </div>
</body>
</html>