<?php
    echo $this->head()
            ->meta('Author', 'Wesley Overdijk')
            ->addCss($this->themePath.'/css/default.css')
            ->titleSeperator(' - ')
            ->appendTitle('Some random page title.')
            ->setContentType()
            ->appendTitle('An adition to the page title')
            //This would normally kill the 2 page titles (overwrite them)
            #->setTitle('I killed the 2 appended titles lol')
            ->disableCache();
?>
<body>
    <div id="pageWrapper">
        <div id="header">
            <p>#header</p>
        </div>
        <div id="nav">
            <p>#nav</p>
        </div>
        <div id="sidebar">
            <div id="subNav">
                <p>#subNav</p>
            </div>
            <div id="adminMenu">
                <p>#adminMenu</p>
            </div>
            <div id="userForm">
                <p>#userForm</p>
            </div>
                <p>#sidebar</p>
        </div>
        <div id="main">
            <h1>
                Pagetitle
            </h1>
            <h2>
                Some description
            </h2>
            <p>
                <?php echo $this->layout()->content; ?>
            </p>
        </div>
        <div id="footer">
            <p>Copyright 2009/ 2010. blabla All rights reserved. Powered by xswcms</p>
        </div>
    </div>
</body>
</html>