<?php
    echo '<?xml version="1.0" encoding="UTF-8" ?>';
    echo $this->doctype();
?>
<html>
<head>
    <title><?php echo $this->headTitle; ?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php $this->headLink()->appendStylesheet($this->basePath.'/css/default.css'); echo $this->headLink();?>
</head>
<body>
    <div id="pageWrapper">
        <div id="header">
            <p>#header</p>
        </div>
        <div id="nav">
            <p>#nav</p>
        </div>
        <div id="sidebar">
            <div id="subNav">
                <p>#subNav</p>
            </div>
            <div id="adminMenu">
                <p>#adminMenu</p>
            </div>
            <div id="userForm">
                <p>#userForm</p>
            </div>
                <p>#sidebar</p>
        </div>
        <div id="main">
            <h1>
                Pagetitle
            </h1>
            <h2>
                Some description
            </h2>
            <p>
                <?php echo $this->layout()->content; ?>
            </p>
        </div>
        <div id="footer">
            <p>Copyright 2009/ 2010. blabla All rights reserved. Powered by xswcms</p>
        </div>
    </div>
</body>
</html>